version: "3.9"
services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: none
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgresql://user:password@db:5432/taes?sslmode=disable